### ISSUE TITLE
Resources fail to load when pwx is installed in a directory

### ISSUE THREAD

**Issue by joseluis** [MichaelThessel/pwx#15]
When pwx is installed in a subdomain all loads fine, but when it's installed in a subfolder then the js / css files are not loaded because the app tries to load them from the root folder:

/css/style.css
/js/hideShowPassword.min.js
/js/jquery.zclip.min.js
/js/script.js

**Comment by MichaelThessel** [comment]
This actually broke some functionality. The password view page itself has a relative path and wouldn't load js+css anymore. I added a baseUrl config setting. Check #21 for reference.
