### ISSUE TITLE
Add REST API

### ISSUE THREAD

**Issue by MichaelThessel** [MichaelThessel/pwx#29]

**Comment by rabbl** [comment]
I had very nice experience with Symfony and fosRestBundle.
Have a look here: https://bin.binee.co/api/doc
Do you know if FOSRest works with Silex?

**Comment by MichaelThessel** [comment]
I will look into it. This is the first Silex/Symfony project I have done. I usually use ZF2. When I started PWX I was looking into micro frameworks and found Silex to be pretty interesting. The API is not so important at this point. I added the ticket to keep it in mind for the future. I could see this to be an interesting feature for hosting companies and such.

**Comment by MichaelThessel** [comment]
Thanks for implementing this!
