### ISSUE TITLE
Make it translation ready

### ISSUE THREAD

**Issue by joseluis** [MichaelThessel/pwx#3]
It would be very useful to be able to load different translations from po files depending on the locale of the browser.

**Comment by MichaelThessel** [comment]
Good point. Would you be willing to contribute a translation? I could do German and English.

**Comment by joseluis** [comment]
I can translate it to spanish, yes

**Comment by MichaelThessel** [comment]
Ok, give me a bit. I'm on vacation atm. I will get back to you once I got everything ready.

**Comment by joseluis** [comment]
Ok, it's a deal

**Comment by MichaelThessel** [comment]
Jose, I translated the app. You can add your Spanish translations [here](https://github.com/MichaelThessel/pwx/blob/master/app/locales/es.yml) For now I added a [config switch for the language](https://github.com/MichaelThessel/pwx/blob/master/app/config.php.sample#L12) that corresponds to the locale file name (es).

**Comment by joseluis** [comment]
Hey Michael, I've created a pull request #5

**Comment by MichaelThessel** [comment]
Merged it. Thanks!
