### ISSUE TITLE
Add the possibility of choosing the display language with GET parameters 

### ISSUE THREAD

**Issue by joseluis** [MichaelThessel/pwx#36]
e.g.: `https://pwx.example.com/?lang=es`

This would be fantastic for further integrating this tool with multilingual websites

**Comment by MichaelThessel** [comment]
I implemented that. To keep things consistent with the code I named the parameter `locale`. You can use:

```
https://pwx.example.com/?locale=es
```

now.

**Comment by MichaelThessel** [comment]
Referenced the wrong ticket in commit. The commit can be found here 83361d9019ed42b5be74cac08b6381526ecfa86c

**Comment by joseluis** [comment]
Fantastic!!
