### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rabbl** [MichaelThessel/pwx#9]

**Comment by MichaelThessel** [comment]
Tests would be awesome. We could get one of those sweet TravisCI badges. :)

**Comment by MichaelThessel** [comment]
Merged #11. I will add some more test cases and integrate with TravisCI.

**Comment by MichaelThessel** [comment]
Integrated with Travis CI #12

**Comment by MichaelThessel** [comment]
I will close this for now and we can add individual tickets for individual tests.
